apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: gym-app
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_APPLICATION_NAME
              value: "booking-service"
            - name: GYM_SERVICE_URL
              value: "http://gym-service.gym-app.svc.cluster.local:8080"
            - name: GYM_SERVICE_TIMEOUT
              value: "3"
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
