apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: gym-app
  labels:
    app: booking-service
spec:
  type: NodePort
  selector:
    app: booking-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
