apiVersion: v1
kind: Service
metadata:
  name: gym-service
  namespace: gym-app
  labels:
    app: gym-service           # el ServiceMonitor busca este label
spec:
  type: NodePort
  selector:
    app: gym-service
  ports:
    - name: http               # nombre requerido por el ServiceMonitor
      port: 8080
      targetPort: 8080
      nodePort: 30080
