apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gym-service-monitor
  namespace: gym-app
  labels:
    release: prometheus           # debe coincidir con el label del Prometheus Operator
spec:
  selector:
    matchLabels:
      app: gym-service            # coincide exactamente con el label del Service
  endpoints:
    - port: http                  # nombre del puerto en el Service
      path: /actuator/metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - gym-app
