server:
  port: 8080

spring:
  application:
    name: gym-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
